[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bsix"
version = "0.0.4"
authors = [
    {name = "Francisco Moreno Cano", email = "francisco.moreno@uco.es"}
]
description = "Benchmarking Survival analysis: Inference and eXplainability."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
license-files = ["LICENSE"]
dependencies = [
    "config>=0.5.1",
    "h5py>=3.16",
    "joblib>=1.6",
    "lifelines>=0.30",
    "matplotlib>=3.11",
    "memory_profiler>=0.61",
    "mplcursors>=0.7",
    "numba>=0.67",
    "numpy>=2.5",
    "pandas>=3.0",
    "pycox>=0.3",
    "remayn>=1.0",
    "sacred>=0.8",
    "scikit_learn>=1.9",
    "scikit-survival>=0.28",
    "scipy>=1.18",
    "shap>=0.52",
    "statsmodels>=0.15",
    "submitit>=1.5",
    "tabpfn>=9.0",
    "torch>=2.14",
    "torchtuples>=0.2",
]

[project.urls]
Source = "https://github.com/ayrna/bsix"

[project.optional-dependencies]
tutorial = [
    "jupyter",
    "ipywidgets",
    "ipympl",
]

[tool.setuptools.package-data]
"bsix.datasets" = ["*"]

[tool.setuptools.exclude-package-data]
"bsix.datasets.beatriz" = ["*"]